management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
#    circuit-breaker-aspect-order: 1
    instances:
      userService:
        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 35s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#  retry:
#    retry-aspect-order: 2
#    instances:
#      userServiceRetry:
#        maxRetryAttempts: 2
#        waitDuration: 500











